// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CartList: typeof import('./src/components/CartList.vue')['default']
    MapPage: typeof import('./src/components/MapPage.vue')['default']
    MyLoading: typeof import('./src/components/MyLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TasteSelection: typeof import('./src/components/TasteSelection.vue')['default']
    ToTop: typeof import('./src/components/ToTop.vue')['default']
  }
}
